language: node_js
node_js:
  - "0.11"

before_install:
  - npm install -g gulp

script:
  - gulp

after_script:
  - gulp coveralls && rm -rf ./coverage

after_success:
  - "chmod +x util/dist.sh"
  - "util/dist.sh"
